version: '3'

services:
  web:
    build: ./
    container_name: tool
    volumes:
      - ./
    restart: always  
    ports:
        - "5000:5000"
    networks:
        - tool
    tty: true
networks: 
  tool:
volumes:
  tool: